# Generated by Django 2.0.5 on 2018-12-09 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languagefinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.TextField(),
        ),
    ]
